controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster: # Name of the joint state broadcaster
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:  # Name of the diff drive controller
      type: diff_drive_controller/DiffDriveController

    arm_joints_controller:  # Name of the arm joints controller
      type: forward_command_controller/ForwardCommandController

diff_drive_controller: # Name follow you named the diff drive controller above
  ros__parameters:
    left_wheel_names: ["base_left_wheel_joint"] # Name of URDF the left wheel joint
    right_wheel_names: ["base_right_wheel_joint"] # Name of URDF the right wheel joint

    wheel_separation: 0.45
    wheel_radius: 0.1

    odom_frame_id: "odom" # usually odom
    base_frame_id: "base_footprint" # usually URDF base_footprint or base_link

    # give the covariance values for the odometry
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    enable_odom_tf: true
    publish_rate: 50.0 # Hz publish rate must smaller than update_rate

    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0

arm_joints_controller:
  ros__parameters:
    joint_names: ["arm_joint1", "arm_joint2"] # Names of the arm joints in URDF
    interface_name: position # Control interface type (position, velocity, effort)